language: php
php:
  - '7.0'
  - '7.1'

install:
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpunit run --coverage --coverage-xml

after_success:
  - php vendor/bin/php-coveralls
