env:
  global:
    - CC_TEST_REPORTER_ID=2658e3c672826dc096db43dad7a1ceca2147dbe5f3c7cdfc89ee1187494e9554

language: php
php:
  - '7.0'
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `dbal-test`;'

install:
  - composer self-update
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - php vendor/bin/phpunit --config phpunit.travis.xml

after_success:
  - php vendor/bin/php-coveralls

after_script:
  - ./cc-test-reporter-upload-coverage -i ./Test/Output/coverage.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT