language: php
php:
  - '7.0'
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `dbal-test`;'

install:
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpunit --config phpunit.travis.xml

after_success:
  - php vendor/bin/php-coveralls
